spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 12345
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/cloud_1?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8
    druid:
      max-active: 100
  application:
    name: orderService
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  redis:
    host: 47.98.152.214
    port: 9736
    database: 1
    timeout: 5000
    lettuce:
      pool:
        max-active: 100
        max-idle: 5
        max-wait: -1
        min-idle: 0
server:
  port: 8083

mybatis:
  type-aliases-package: com.testLock.entites
  mapper-locations: classpath:mapper/*.xml
